#!/bin/bash

dart pub global activate protoc_plugin
go install github.com/apptreesoftware/protoc-gen-twirp_dart@v0.0.0-20190501115218-4aa481ad603f
go install github.com/twitchtv/twirp/protoc-gen-twirp@v8.1.0+incompatible
