on:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
  restrict:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "yolo"

